export default [
  {
    company: "ByteDance",
    location: "Singapore, Onsite, Intern",
    time: "May 2025 - Oct 2025",
    job: "Software Engineer",
    description: [
      "Contributed to the Global Payments Compliance team, developing Know-Your-Customer (KYC) workflows to strengthen financial compliance and user safety across ByteDance/TikTok’s international markets.",
      "Led the development of a KYC workflow to support TikTok’s Refund-to-Credit rollout in Thailand, reducing suspicious fund activity by 9%.",
      "Introduced a backup KYC vendor for TikTok's User Growth business line in Japan, eliminating a single point of failure and ensuring continuous compliance processing during vendor outages.",
      "Optimised KYC workflow with an optical character recognition (OCR)-only solution for ByteDance’s upstream business lines, accelerating document processing by reducing OCR result retrieval time by 45%.",
      "Designed an automated KYC vendor evaluation system in Go, leveraging goroutines and concurrency primitives for faster asynchronous processing, reducing manual effort by 30% and streamlining vendor management.",
    ],
    skills: ["Go", "Goroutines", "RPC", "Distributed Systems"],
    testimonials: "",
  },
  {
    company: "SAP",
    location: "Singapore, Onsite, Intern",
    time: "Jan 2025 - May 2025",
    job: "Full Stack Software Developer",
    description: [
      "Joined the Singapore AI Labs team, contributing to infrastructure and internal tooling for SAP’s personalised recommendation services used by SAP SuccessFactors.",
      "Deployed Dynatrace and Grafana dashboards for SAP’s personalised recommendation services on CloudFoundry, enabling real-time metric tracking and reducing issue resolution time by 20%.",
      "Designed and implemented an automated data purging background service, reducing database storage overhead by 15%, preventing performance degradation, and ensuring long-term database stability.",
      "Built and integrated performance testing into the Jenkins CI/CD pipeline, automating reporting and reducing manual intervention by 40%, thereby accelerating system performance feedback loops.",
    ],
    skills: ["Python", "Grafana", "Jenkins", "CloudFoundry"],
    testimonials: "true",
  },
  {
    company: "Carbon GPT",
    location: "Malaysia, Remote, Intern",
    time: "Aug 2024 - Dec 2024",
    job: "Software Engineer",
    description: [
      "Collaborated with developers to debug issues and implement comprehensive unit and integration tests leveraging Pytest, achieving 100% code coverage and significantly improving software reliability.",
      "Wrote a custom migration script and migrated over 100GB of data using Alembic, ensuring seamless PostgreSQL transitions with zero data loss and maintaining 99.9% system uptime.",
      "Led the adoption of Pylint for static analysis across the team, enhancing code quality, enforcing coding standards, and reducing technical debt by preventing code smells.",
    ],
    skills: ["Python", "PostgreSQL", "Alembic", "Pytest"],
    testimonials: "",
  },
  {
    company: "Micron Technology",
    location: "Singapore, Onsite, Intern",
    time: "May 2024 - Aug 2024",
    job: "SSD Firmware Validation Developer",
    description: [
      "Worked with the Product Engineering team, focusing on firmware validation and data-driven reliability improvements for Micron’s SSD product line.",
      "Designed a smart automation system to collect and analyse time series SSD test data, reducing teams’ manual data processing time by 40% and expediting real-time decision-making.",
      "Developed an interactive dashboard using React.js, Redux, and Tailwind CSS for real-time anomaly visualisation, integrating FastAPI with a PostgreSQL database and a machine learning service to enhance data insights.",
      "Implemented unsupervised machine learning algorithms using Scikit-learn and Keras/TensorFlow to detect anomalies in datasets, achieving an 87% detection rate and enabling early identification of potential firmware issues.",
    ],
    skills: ["React.js", "FastAPI", "PostgreSQL", "TensorFlow"],
    testimonials: "true",
  },
];
